apiVersion: 1

datasources:
  - name: PaperLeaf Prometheus
    uid: paperleaf-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
